In [5]:
import pandas as pd
import numpy as np

s = pd.Series([1, 3, 5, np.nan, 6, 8])
print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


In [8]:
dates = pd.date_range("20241008", periods=8)
print(dates)
df = pd.DataFrame(np.random.randn(8, 4), index = dates, columns=list("ABCD"))
print(df)

DatetimeIndex(['2024-10-08', '2024-10-09', '2024-10-10', '2024-10-11',
               '2024-10-12', '2024-10-13', '2024-10-14', '2024-10-15'],
              dtype='datetime64[ns]', freq='D')
                   A         B         C         D
2024-10-08 -0.247824  0.452351 -0.448261  0.326955
2024-10-09  1.615711 -0.065182  0.804019  1.279837
2024-10-10  0.057717 -0.955387 -1.698616  0.843754
2024-10-11  1.193516 -2.056535  0.872157  0.988332
2024-10-12 -2.319075 -0.633824 -2.675227  0.899992
2024-10-13 -0.897090  0.572100 -1.099331 -1.448142
2024-10-14  0.167591 -1.212741 -1.181626  1.108857
2024-10-15 -0.171698  0.133443  0.911219 -0.902266


In [12]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype = "float32"),
        "D": np.array([3]*4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
print(df2)
print(df2.index)
print(df2.columns)
print(df2.dtypes)

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo
Index([0, 1, 2, 3], dtype='int64')
Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')
A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object


In [14]:
print(df.head())
print(df.tail())

                   A         B         C         D
2024-10-08 -0.247824  0.452351 -0.448261  0.326955
2024-10-09  1.615711 -0.065182  0.804019  1.279837
2024-10-10  0.057717 -0.955387 -1.698616  0.843754
2024-10-11  1.193516 -2.056535  0.872157  0.988332
2024-10-12 -2.319075 -0.633824 -2.675227  0.899992
                   A         B         C         D
2024-10-11  1.193516 -2.056535  0.872157  0.988332
2024-10-12 -2.319075 -0.633824 -2.675227  0.899992
2024-10-13 -0.897090  0.572100 -1.099331 -1.448142
2024-10-14  0.167591 -1.212741 -1.181626  1.108857
2024-10-15 -0.171698  0.133443  0.911219 -0.902266


In [22]:
print(df.to_numpy())
print(df.describe(percentiles=[.25, .5]))

[[-0.24782387  0.45235076 -0.44826101  0.32695511]
 [ 1.61571143 -0.06518204  0.80401872  1.27983699]
 [ 0.05771701 -0.95538693 -1.69861595  0.84375401]
 [ 1.19351572 -2.05653505  0.87215704  0.98833171]
 [-2.31907469 -0.63382389 -2.67522657  0.89999225]
 [-0.89709046  0.57209967 -1.09933141 -1.44814218]
 [ 0.16759081 -1.21274065 -1.18162636  1.10885744]
 [-0.17169831  0.13344262  0.91121874 -0.90226587]]
              A         B         C         D
count  8.000000  8.000000  8.000000  8.000000
mean  -0.075144 -0.470722 -0.564458  0.387165
std    1.212731  0.909938  1.338248  1.013141
min   -2.319075 -2.056535 -2.675227 -1.448142
25%   -0.410141 -1.019725 -1.310874  0.019650
50%   -0.056991 -0.349503 -0.773796  0.871873
max    1.615711  0.572100  0.911219  1.279837


In [23]:
df.T

   2024-10-08  2024-10-09  2024-10-10  2024-10-11  2024-10-12  2024-10-13  \
A   -0.247824    1.615711    0.057717    1.193516   -2.319075   -0.897090   
B    0.452351   -0.065182   -0.955387   -2.056535   -0.633824    0.572100   
C   -0.448261    0.804019   -1.698616    0.872157   -2.675227   -1.099331   
D    0.326955    1.279837    0.843754    0.988332    0.899992   -1.448142   

   2024-10-14  2024-10-15  
A    0.167591   -0.171698  
B   -1.212741    0.133443  
C   -1.181626    0.911219  
D    1.108857   -0.902266  


In [27]:
print(df.sort_values(by="B"))
print(df.sort_index())

                   A         B         C         D
2024-10-11  1.193516 -2.056535  0.872157  0.988332
2024-10-14  0.167591 -1.212741 -1.181626  1.108857
2024-10-10  0.057717 -0.955387 -1.698616  0.843754
2024-10-12 -2.319075 -0.633824 -2.675227  0.899992
2024-10-09  1.615711 -0.065182  0.804019  1.279837
2024-10-15 -0.171698  0.133443  0.911219 -0.902266
2024-10-08 -0.247824  0.452351 -0.448261  0.326955
2024-10-13 -0.897090  0.572100 -1.099331 -1.448142
                   A         B         C         D
2024-10-08 -0.247824  0.452351 -0.448261  0.326955
2024-10-09  1.615711 -0.065182  0.804019  1.279837
2024-10-10  0.057717 -0.955387 -1.698616  0.843754
2024-10-11  1.193516 -2.056535  0.872157  0.988332
2024-10-12 -2.319075 -0.633824 -2.675227  0.899992
2024-10-13 -0.897090  0.572100 -1.099331 -1.448142
2024-10-14  0.167591 -1.212741 -1.181626  1.108857
2024-10-15 -0.171698  0.133443  0.911219 -0.902266


In [29]:
print(df["A"])
print(df[0:3])
print(df["20241008":"20241011"])

2024-10-08   -0.247824
2024-10-09    1.615711
2024-10-10    0.057717
2024-10-11    1.193516
2024-10-12   -2.319075
2024-10-13   -0.897090
2024-10-14    0.167591
2024-10-15   -0.171698
Freq: D, Name: A, dtype: float64
                   A         B         C         D
2024-10-08 -0.247824  0.452351 -0.448261  0.326955
2024-10-09  1.615711 -0.065182  0.804019  1.279837
2024-10-10  0.057717 -0.955387 -1.698616  0.843754
                   A         B         C         D
2024-10-08 -0.247824  0.452351 -0.448261  0.326955
2024-10-09  1.615711 -0.065182  0.804019  1.279837
2024-10-10  0.057717 -0.955387 -1.698616  0.843754
2024-10-11  1.193516 -2.056535  0.872157  0.988332


In [32]:
print(df.loc[dates[0]])
print(df.loc[:, ["A", "B"]])
print(df.loc["20241008":"20241013", ["A", "B"]])

A   -0.247824
B    0.452351
C   -0.448261
D    0.326955
Name: 2024-10-08 00:00:00, dtype: float64
                   A         B
2024-10-08 -0.247824  0.452351
2024-10-09  1.615711 -0.065182
2024-10-10  0.057717 -0.955387
2024-10-11  1.193516 -2.056535
2024-10-12 -2.319075 -0.633824
2024-10-13 -0.897090  0.572100
2024-10-14  0.167591 -1.212741
2024-10-15 -0.171698  0.133443
                   A         B
2024-10-08 -0.247824  0.452351
2024-10-09  1.615711 -0.065182
2024-10-10  0.057717 -0.955387
2024-10-11  1.193516 -2.056535
2024-10-12 -2.319075 -0.633824
2024-10-13 -0.897090  0.572100
